[package]
name = "ipfs-fuse"
version = "0.0.1"
authors = ["Yann Autissier <aya@asycn.io>"]
description = "IPFS Filesystem in Userspace (FUSE)"
keywords = ["ipfs", "fuse", "filesystem"]
license = "GPL"

[dependencies]
ipfs-api-backend-actix = "0.7"
fuser = "0.12"
